# Generated by Django 5.0 on 2023-12-18 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plane',
            fields=[
                ('id', models.PositiveSmallIntegerField(unique=True)),
                ('plane_id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('litres', models.PositiveSmallIntegerField(default=200)),
                ('passengers', models.PositiveSmallIntegerField()),
            ],
        ),
    ]